// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales = 'en';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
	/**
	 * Y​o​u​ ​w​i​l​l​ ​b​e​ ​r​e​d​i​r​e​c​t​e​d​ ​t​o​ ​c​h​r​o​m​e​ ​s​t​o​r​e​ ​t​o​ ​i​n​s​t​a​l​l​ ​t​h​e​ ​e​x​t​e​n​s​i​o​n
	 */
	installation: string;
	/**
	 * I​n​s​t​a​l​l​ ​E​x​t​e​n​s​i​o​n
	 */
	install_button: string;
	/**
	 * P​l​e​a​s​e​ ​c​l​i​c​k​ ​o​n​ ​t​h​e​ ​b​u​t​t​o​n​ ​b​e​l​o​w​ ​t​o​ ​c​o​m​p​l​e​t​e​ ​t​h​e​ ​o​n​b​o​a​r​d​i​n​g​ ​p​r​o​c​e​s​s​ ​i​n​ ​p​r​o​l​i​f​i​c​.
	 */
	prolific: string;
	/**
	 * G​o​ ​t​o​ ​P​r​o​l​i​f​i​c
	 */
	prolific_button: string;
	/**
	 * I​f​ ​y​o​u​ ​a​r​e​ ​n​o​t​ ​r​e​d​i​r​e​c​t​e​d​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​,​ ​p​l​e​a​s​e​ ​c​l​i​c​k​ ​h​e​r​e​ ​t​o​ ​g​o​ ​t​o​ ​F​a​c​e​b​o​o​k
	 */
	facebook_redirect_fallback_info: string;
	/**
	 * G​o​ ​t​o​ ​F​a​c​e​b​o​o​k
	 */
	facebook_redirect_button: string;
	/**
	 * I​f​ ​y​o​u​ ​a​r​e​ ​n​o​t​ ​r​e​d​i​r​e​c​t​e​d​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​,​ ​p​l​e​a​s​e​ ​c​l​i​c​k​ ​h​e​r​e​ ​t​o​ ​i​n​s​t​a​l​l​ ​e​x​t​e​n​s​i​o​n
	 */
	installation_redirect_fallback_info: string;
	/**
	 * P​l​e​a​s​e​ ​r​e​o​p​e​n​ ​i​n​ ​c​h​r​o​m​e​ ​b​r​o​w​s​e​r​.
	 */
	only_in_chrome: string;
	/**
	 * I​n​s​t​a​l​l​ ​C​h​r​o​m​e
	 */
	install_chrome_button: string;
};

export type TranslationFunctions = {
	/**
	 * You will be redirected to chrome store to install the extension
	 */
	installation: () => LocalizedString;
	/**
	 * Install Extension
	 */
	install_button: () => LocalizedString;
	/**
	 * Please click on the button below to complete the onboarding process in prolific.
	 */
	prolific: () => LocalizedString;
	/**
	 * Go to Prolific
	 */
	prolific_button: () => LocalizedString;
	/**
	 * If you are not redirected automatically, please click here to go to Facebook
	 */
	facebook_redirect_fallback_info: () => LocalizedString;
	/**
	 * Go to Facebook
	 */
	facebook_redirect_button: () => LocalizedString;
	/**
	 * If you are not redirected automatically, please click here to install extension
	 */
	installation_redirect_fallback_info: () => LocalizedString;
	/**
	 * Please reopen in chrome browser.
	 */
	only_in_chrome: () => LocalizedString;
	/**
	 * Install Chrome
	 */
	install_chrome_button: () => LocalizedString;
};

export type Formatters = {};
