// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * P​l​e​a​s​e​ ​c​l​i​c​k​ ​b​e​l​o​w​ ​t​o​ ​i​n​s​t​a​l​l​ ​t​h​e​ ​e​x​t​e​n​s​i​o​n​.​.​.
	 */
	installation: string
	/**
	 * I​n​s​t​a​l​l​ ​E​x​t​e​n​s​i​o​n
	 */
	install_button: string
	/**
	 * P​l​e​a​s​e​ ​c​l​i​c​k​ ​o​n​ ​t​h​e​ ​b​u​t​t​o​n​ ​b​e​l​o​w​ ​t​o​ ​c​o​m​p​l​e​t​e​ ​t​h​e​ ​o​n​b​o​a​r​d​i​n​g​ ​p​r​o​c​e​s​s​ ​i​n​ ​p​r​o​l​i​f​i​c​.
	 */
	prolific: string
	/**
	 * G​o​ ​t​o​ ​P​r​o​l​i​f​i​c
	 */
	prolific_button: string
	/**
	 * I​f​ ​y​o​u​ ​a​r​e​ ​n​o​t​ ​r​e​d​i​r​e​c​t​e​d​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​,​ ​p​l​e​a​s​e​ ​c​l​i​c​k​ ​h​e​r​e​ ​t​o​ ​g​o​ ​t​o​ ​F​a​c​e​b​o​o​k
	 */
	study: string
	/**
	 * G​o​ ​t​o​ ​F​a​c​e​b​o​o​k
	 */
	study_button: string
	/**
	 * T​h​i​s​ ​o​n​l​y​ ​w​o​r​k​s​ ​i​n​ ​C​h​r​o​m​e
	 */
	only_in_chrome: string
}

export type TranslationFunctions = {
	/**
	 * Please click below to install the extension...
	 */
	installation: () => LocalizedString
	/**
	 * Install Extension
	 */
	install_button: () => LocalizedString
	/**
	 * Please click on the button below to complete the onboarding process in prolific.
	 */
	prolific: () => LocalizedString
	/**
	 * Go to Prolific
	 */
	prolific_button: () => LocalizedString
	/**
	 * If you are not redirected automatically, please click here to go to Facebook
	 */
	study: () => LocalizedString
	/**
	 * Go to Facebook
	 */
	study_button: () => LocalizedString
	/**
	 * This only works in Chrome
	 */
	only_in_chrome: () => LocalizedString
}

export type Formatters = {}
