// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * P​l​e​a​s​e​ ​c​l​i​c​k​ ​b​e​l​o​w​ ​t​o​ ​i​n​s​t​a​l​l​ ​t​h​e​ ​e​x​t​e​n​s​i​o​n​.​.​.
	 */
	installation: string
	/**
	 * I​n​s​t​a​l​l​ ​E​x​t​e​n​s​i​o​n
	 */
	install_button: string
	/**
	 * P​l​e​a​s​e​ ​c​l​i​c​k​ ​o​n​ ​t​h​e​ ​b​u​t​t​o​n​ ​b​e​l​o​w​ ​t​o​ ​c​o​m​p​l​e​t​e​ ​t​h​e​ ​o​n​b​o​a​r​d​i​n​g​ ​p​r​o​c​e​s​s​ ​i​n​ ​p​r​o​l​i​f​i​c​.
	 */
	prolific: string
	/**
	 * G​o​ ​t​o​ ​P​r​o​l​i​f​i​c
	 */
	prolific_button: string
	/**
	 * C​l​i​c​k​ ​b​e​l​o​w​ ​t​o​ ​c​o​n​t​i​n​u​e​ ​t​h​e​ ​s​t​u​d​y
	 */
	study: string
	/**
	 * G​o​ ​t​o​ ​F​a​c​e​b​o​o​k
	 */
	study_button: string
}

export type TranslationFunctions = {
	/**
	 * Please click below to install the extension...
	 */
	installation: () => LocalizedString
	/**
	 * Install Extension
	 */
	install_button: () => LocalizedString
	/**
	 * Please click on the button below to complete the onboarding process in prolific.
	 */
	prolific: () => LocalizedString
	/**
	 * Go to Prolific
	 */
	prolific_button: () => LocalizedString
	/**
	 * Click below to continue the study
	 */
	study: () => LocalizedString
	/**
	 * Go to Facebook
	 */
	study_button: () => LocalizedString
}

export type Formatters = {}
